name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "checkout source"
        uses: actions/checkout@v3
      
      - name: "checkout target"
        uses: actions/checkout@v3
          repository: git@github.com:asstart/vault.git

      - name: "test"
        uses: asstart/obsidian-publish-action@5e94e69f1429bc517ffc05312fd31ca0448d58fe