name: Publish

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        uses: asstart/obsidian-publish-jsaction/actions/compose@f/fix-push-root
        with:
          token: ${{ secrets.OBISDIAN_PUBLISH_TOKEN }}
          publishAll: true
