name: Publish Same Repo Full Conf

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "publish"
        uses: asstart/obsidian-publish-jsaction/actions/compose@main
        with:
          targetRepo: asstart/obsidian-publish-action-test
          targetBranch: gh-pages-fullconf
          sourceFolder: .
          targetFolder: .
          tags: example
          publishAll: false
          jekyllTheme: just-the-docs
          jekyllTitle: Full Conf Example
          jekyllDescription: It's description of my obsidian site
          colorSchema: dark
