name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        uses: asstart/obsidian-publish-jsaction/actions/compose@60b9f93af4ca94c21f84549f3ad49c04584c7051
        with:
          token: ${{ secrets.OBISDIAN_PUBLISH_TOKEN }}
          repo: asstart/vault
