name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        uses: asstart/obsidian-publish-action@c97593c6fdc445644f307ea1f68cf33a267967b3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
