name: Publish Separate Repo Docs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "publish"
        uses: asstart/obsidian-publish-jsaction/actions/compose@main
        with:
          token: ${{ secrets.OBISDIAN_PUBLISH_TOKEN }}
          publishAll: true
          targetRepo: asstart/obsidian-publish-action-test-sep
          targetFolder: docs
          targetBranch: gh-pages-docs
