name: Publish Separate Repo Root

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "publish"
        uses: asstart/obsidian-publish-jsaction/actions/compose@f/fix-push-root
        with:
          token: ${{ secrets.OBISDIAN_PUBLISH_TOKEN }}
          publishAll: true
          targetRepo: asstart/obsidian-publish-action-test-sep
          targetBranch: gh-pages-root
