name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        uses: asstart/obsidian-publish-action@08ecfcd4995b72f5389fe148dc1d837f76841b8c
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
